spring.application.name=eftmanager

spring.datasource.url=jdbc:postgresql://localhost:5432/${DB_NAME:eftmanager}
spring.datasource.username=${DB_USERNAME:postgres}
spring.datasource.password=${DB_PASSWORD:postgres}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.open-in-view=false

spring.flyway.enabled=true

jwt.secret=${JWT_SECRET}
jwt.expiration-ms=${JWT_EXPIRATION_MS:3600000}

tarkov.api.base-url=${TARKOV_API_URL:https://json.tarkov.dev}
tarkov.api.language=${TARKOV_API_LANGUAGE:es}